export enum SkillIdsEnum {
    INSPIRE = 'INSPIRE',
    UPPERS = 'UPPERS',
    COMBAT_DOCTOR = 'COMBAT_DOCTOR',
    QUICK_FIX = 'QUICK_FIX',
    PAINKILLERS = 'PAINKILLERS',
    COMBAT_MEDIC = 'COMBAT_MEDIC',

    HOSTAGE_TAKER = 'HOSTAGE_TAKER',
    STOCKHOLM_SYNDROME = 'STOCKHOLM_SYNDROME',
    PARTNERS_IN_CRIME = 'PARTNERS_IN_CRIME',
    CONFIDENT = 'CONFIDENT',
    JOKER = 'JOKER',
    FORCED_FRIENDSHIP = 'FORCED_FRIENDSHIP',

    GRAZE = 'GRAZE',
    AMMO_EFFICIENCY = 'AMMO_EFFICIENCY',
    AGGRESSIVE_RELOAD = 'AGGRESSIVE_RELOAD',
    RIFLEMAN = 'RIFLEMAN',
    MARKSMAN = 'MARKSMAN',
    STABLE_SHOT = 'STABLE_SHOT',

    OVERKILL = 'OVERKILL',
    FAR_AWAY = 'FAR_AWAY',
    CLOSE_BY = 'CLOSE_BY',
    SHOTGUN_CQB = 'SHOTGUN_CQB',
    SHOTGUN_IMPACT = 'SHOTGUN_IMPACT',
    UNDERDOG = 'UNDERDOG',

    IRON_MAN = 'IRON_MAN',
    SHOCK_AND_AWE = 'SHOCK_AND_AWE',
    BULLSEYE = 'BULLSEYE',
    DIE_HARD = 'DIE_HARD',
    TRANSPORTER = 'TRANSPORTER',
    RESILIENCE = 'RESILIENCE',

    FULLY_LOADED = 'FULLY_LOADED',
    EXTRA_LEAD = 'EXTRA_LEAD',
    SAW_MASSACRE = 'SAW_MASSACRE',
    BULLETSTORM = 'BULLETSTORM',
    PORTABLE_SAW = 'PORTABLE_SAW',
    SCAVENGER = 'SCAVENGER',
}

export enum SubtreeIdsEnum {
    MEDIC = 'MEDIC',
    CONTROLLER = 'CONTROLLER',
    SHARPSHOOTER = 'SHARPSHOOTER',

    SHOTGUNNER = 'SHOTGUNNER',
    TANK = 'TANK',
    AMMO_SPECIALIST = 'AMMO_SPECIALIST',
}

export enum TreeIdsEnum {
    MASTERMIND = 'MASTERMIND',
    ENFORCER = 'ENFORCER',
}