export enum TREE_IDS_ENUM {
    MASTERMIND = 'MASTERMIND',
}

export enum SUBTREE_IDS_ENUM {
    MEDIC = 'MEDIC',
    CONTROLLER = 'CONTROLLER',
    SHARPSHOOTER = 'SHARPSHOOTER',
};

export enum SKILL_IDS_ENUM {
    INSPIRE = 'INSPIRE',
    UPPERS = 'UPPERS',
    COMBAT_DOCTOR = 'COMBAT_DOCTOR',
    QUICK_FIX = 'QUICK_FIX',
    PAINKILLERS = 'PAINKILLERS',
    COMBAT_MEDIC = 'COMBAT_MEDIC',

    HOSTAGE_TAKER = 'HOSTAGE_TAKER',
    STOCKHOLM_SYNDROME = 'STOCKHOLM_SYNDROME',
    PARTNERS_IN_CRIME = 'PARTNERS_IN_CRIME',
    CONFIDENT = 'CONFIDENT',
    JOKER = 'JOKER',
    FORCED_FRIENDSHIP = 'FORCED_FRIENDSHIP',

    GRAZE = 'GRAZE',
    AMMO_EFFICIENCY = 'AMMO_EFFICIENCY',
    AGGRESSIVE_RELOAD = 'AGGRESSIVE_RELOAD',
    RIFLEMAN = 'RIFLEMAN',
    MARKSMAN = 'MARKSMAN',
    STABLE_SHOT = 'STABLE_SHOT',
}