export enum TREE_IDS_ENUM {
    MASTERMIND = 'MASTERMIND',
    ENFORCER = 'ENFORCER',
    TECHNICIAN = 'TECHNICIAN',
    GHOST = 'GHOST',
}

export enum SUBTREE_IDS_ENUM {
    MEDIC = 'MEDIC',
    CONTROLLER = 'CONTROLLER',
    SHARPSHOOTER = 'SHARPSHOOTER',

    SHOTGUNNER = 'SHOTGUNNER',
    TANK = 'TANK',
    AMMO_SPECIALIST = 'AMMO_SPECIALIST',

    ENGINEER = 'ENGINEER',
    BREACHER = 'BREACHER',
    OPPRESSOR = 'OPPRESSOR',

    SHINOBI = 'SHONOBI',
    ARTFUL_DODGER = 'ARTFUL_DODGER',
    SILENT_KILLER = 'SILENT_KILLER',
};

export enum SKILL_IDS_ENUM {
    INSPIRE = 'INSPIRE',
    UPPERS = 'UPPERS',
    COMBAT_DOCTOR = 'COMBAT_DOCTOR',
    QUICK_FIX = 'QUICK_FIX',
    PAINKILLERS = 'PAINKILLERS',
    COMBAT_MEDIC = 'COMBAT_MEDIC',

    HOSTAGE_TAKER = 'HOSTAGE_TAKER',
    STOCKHOLM_SYNDROME = 'STOCKHOLM_SYNDROME',
    PARTNERS_IN_CRIME = 'PARTNERS_IN_CRIME',
    CONFIDENT = 'CONFIDENT',
    JOKER = 'JOKER',
    FORCED_FRIENDSHIP = 'FORCED_FRIENDSHIP',

    GRAZE = 'GRAZE',
    AMMO_EFFICIENCY = 'AMMO_EFFICIENCY',
    AGGRESSIVE_RELOAD = 'AGGRESSIVE_RELOAD',
    RIFLEMAN = 'RIFLEMAN',
    MARKSMAN = 'MARKSMAN',
    STABLE_SHOT = 'STABLE_SHOT',

    OVERKILL = 'OVERKILL',
    FAR_AWAY = 'FAR_AWAY',
    CLOSE_BY = 'CLOSE_BY',
    SHOTGUN_CQB = 'SHOTGUN_CQB',
    SHOTGUN_IMPACT = 'SHOTGUN_IMPACT',
    UNDERDOG = 'UNDERDOG',
    
    IRON_MAN = 'IRON_MAN',
    SHOCK_AND_AWE = 'SHOCK_AND_AWE',
    BULLSEYE = 'BULLSEYE',
    DIE_HARD = 'DIE_HARD',
    TRANSPORTER = 'TRANSPORTER',
    RESILIENCE = 'RESILIENCE',

    FULLY_LOADED = 'FULLY_LOADED',
    EXTRA_LEAD = 'EXTRA_LEAD',
    SAW_MASSACRE = 'SAW_MASSACRE',
    BULLETSTORM = 'BULLETSTORM',
    PORTABLE_SAW = 'PORTABLE_SAW',
    SCAVENGER = 'SCAVENGER',

    TOWER_DEFENSE = 'TOWER_DEFENSE',
    ENGINEERING = 'ENGINEERING',
    JACK_OF_ALL_TRADES = 'JACK_OF_ALL_TRADES',
    SENTRY_TARGETING_PACKAGE = 'SENTRY_TARGETING_PACKAGE',
    ECO_SENTRY = 'ECO_SENTRY',
    THIRD_LAW = 'THIRD_LAW',

    FIRE_TRAP = 'FIRE_TRAP',
    MORE_FIREPOWER = 'MORE_FIREPOWER',
    KICKSTARTER = 'KICKSTARTER',
    COMBAT_ENGINEERING = 'COMBAT_ENGINEERING',
    DRILL_SAWGEANT = 'DRILL_SAWGEANT',
    HARDWARE_EXPERT = 'HARDWARE_EXPERT',

    BODY_EXPERTISE = 'BODY_EXPERTISE',
    LOCK_N_LOAD = 'LOCK_N_LOAD',
    SUREFIRE = 'SUREFIRE',
    HEAVY_IMPACT = 'HEAVY_IMPACT',
    FIRE_CONTROL = 'FIRE_CONTROL',
    STEADY_GRIP = 'STEADY_GRIP',

    ECM_SPECIALIST = 'ECM_SPECIALIST',
    NIMBLE = 'NIMBLE',
    ECM_OVERDRIVE = 'ECM_OVERDRIVE',
    CLEANER = 'CLEANER',
    SIXTH_SENSE = 'SIXTH_SENSE',
    CHAMELEON = 'CHAMELEON',

    SNEAKY_BASTARD = 'SNEAKY_BASTARD',
    DIRE_NEED = 'DIRE_NEED',
    SHOCKPROOF = 'SHOCKPROOF',
    PARKOUR = 'PARKOUR',
    INNER_POCKETS = 'INNER_POCKETS',
    DUCK_AND_COVER = 'DUCK_AND_COVER',

    UNSEEN_STRIKE = 'UNSEEN_STRIKE',
    LOW_BLOW = 'LOW_BLOW',
    HIGH_VALUE_TARGET = 'HIGH_VALUE_TARGET',
    OPTICAL_ILLUSIONS = 'OPTICAL_ILLUSIONS',
    THE_PROFESSIONAL = 'THE_PROFESSIONAL',
    SECOND_WIND = 'SECOND_WIND',
}